### ISSUE TITLE
Version 3.2 - Failing to update data

### ISSUE THREAD

**Issue by blew1234** [briis/meteobridge#17]
I've just updated to version 3.2, after sorting my previous issues.

The integration has installed correctly, and on HA startup, the data is populated correctly. However, the integration does not then update the data again unless you restart it, at which point it goes around the same loop - updates once, then stops updating.

I have tried changing the update interval, but I still get the same issue.

**Comment by briis** [comment]
I cannot recreate this at my end, trying with to different Meteobridge devices. Could you try and turn on debug, as described in the README file, and see if you get something in the Log.

Also what is your setup - Meteobridge Device, FW Version and Home Assistant Version.

**Comment by blew1234** [comment]
Ok - let me get that setup and I will report back. As for the other details:

Meteobridge Device: Meteobridge Nano SD
FW Version: 1.4 (version 5.2 of software)
HA version: core 2021.11.5

I am getting the following error in the 'core' log:

2021-12-01 08:48:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 186, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/meteobridge/binary_sensor.py", line 92, in is_on
    getattr(self.coordinator.data, self.entity_description.key)
AttributeError: 'ObservationDescription' object has no attribute 'is_lowbat'

**Comment by briis** [comment]
Yes, I just found that error. I removed the Low Battery from the dataset, as it was un-reliable with different Weather Stations, but I forgot to remove it from the Binary Sensors. Will post an update right away.

**Comment by blew1234** [comment]
Ah ok. It does appear that the integration is working, but that bug is causing it to not update the entity.

2021-12-01 08:58:13 DEBUG (MainThread) [custom_components.meteobridge] Finished fetching meteobridge data in 2.493 seconds (success: True)
2021-12-01 08:58:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 186, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/meteobridge/binary_sensor.py", line 92, in is_on
    getattr(self.coordinator.data, self.entity_description.key)
AttributeError: 'ObservationDescription' object has no attribute 'is_lowbat'

**Comment by briis** [comment]
Version 3.2.1 is now out. It should show up in HACS in a short while.
Please report back here if this fixes your issue.

**Comment by blew1234** [comment]
Installed and working fine for the last 30 mins or so. Looks like that's got it.

Thank you for sorting it so quickly!
