### ISSUE TITLE
Some unknown errors

### ISSUE THREAD

**Issue by legi1** [briis/meteobridge#3]
Good morning, I just discovered some Log entries after restarting HASS.
Is this a wrong config on my side?
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/src/homeassistant/homeassistant/components/upnp/sensor.py", line 89, in async_setup_entry
    device: Device = hass.data[DOMAIN]["devices"][udn]
KeyError: 'uuid:4533e9c7-2b08-4bac-9e9d-743d972b6ac7'
2020-07-05 08:14:45 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-07-05 08:14:45 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 10 seconds.
2020-07-05 08:14:55 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.temperature=19.6; attribution=Powered by Meteobridge, brand=Meteobridge, station_hw=Meteobridge Nano, station_ip=192.168.1.209, unit_of_measurement=°C, friendly_name=Temperature, icon=mdi:thermometer, device_class=temperature @ 2020-07-05T08:14:55.016080+02:00> (Offending entity: ?)
2020-07-05 08:14:59 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-07-05 08:14:59 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 20 seconds.
2020-07-05 08:15:06 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.temperature=19.7; attribution=Powered by Meteobridge, brand=Meteobridge, station_hw=Meteobridge Nano, station_ip=192.168.1.209, unit_of_measurement=°C, friendly_name=Temperature, icon=mdi:thermometer, device_class=temperature @ 2020-07-05T08:15:06.647188+02:00> (Offending entity: ?)
2020-07-05 08:15:15 ERROR (SyncWorker_3) [homeassistant.components.command_line.sensor] Command failed: echo $ ((' cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2'))
2020-07-05 08:15:23 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-07-05 08:15:23 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 40 seconds.
2020-07-05 08:16:07 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-07-05 08:16:07 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds.
2020-07-05 08:16:16 ERROR (SyncWorker_9) [homeassistant.components.command_line.sensor] Command failed: echo $ ((' cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2'))
2020-07-05 08:17:17 ERROR (SyncWorker_13) [homeassistant.components.command_line.sensor] Command failed: echo $ ((' cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2'))
2020-07-05 08:17:31 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-07-05 08:17:31 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds.
2020-07-05 08:18:18 ERROR (SyncWorker_11) [homeassistant.components.command_line.sensor] Command failed: echo $ ((' cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2'))
2020-07-05 08:18:55 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-07-05 08:18:55 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds.
2020-07-05 08:19:08 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.temperature=19.8; attribution=Powered by Meteobridge, brand=Meteobridge, station_hw=Meteobridge Nano, station_ip=192.168.1.209, unit_of_measurement=°C, friendly_name=Temperature, icon=mdi:thermometer, device_class=temperature @ 2020-07-05T08:19:08.625258+02:00> (Offending entity: ?)
2020-07-05 08:19:19 ERROR (SyncWorker_17) [homeassistant.components.command_line.sensor] Command failed: echo $ ((' cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2'))

**Comment by briis** [comment]
Hi Peter,
There are a lot of Non Meteobridge related errors in the above, but I can see that it complains about the Temperature value, and it seems that it has a ; attached to the end. I am a bit puzzled about this, as this should not could happen.
Can you go to the *Developer* Tab and press the *STATES* tab. And then find the `sensor.temperature` and let me know what that says? Are the other sensors from Meteobridge Working?

**Comment by legi1** [comment]
Hi Bjarne

 

Thanks for your fast reply. I hope this helps.

 

I think the entries at the beginning are due to the startup procedure. After running a few hours the log looks like this:

 

2020-07-05 11:37:01 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.temperature=24.2; attribution=Powered by Meteobridge, brand=Meteobridge, station_hw=Meteobridge Nano, station_ip=192.168.1.209, unit_of_measurement=°C, friendly_name=Temperature, icon=mdi:thermometer, device_class=temperature @ 2020-07-05T11:37:01.848489+02:00> (Offending entity: ?)

2020-07-05 11:37:25 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.

2020-07-05 11:37:25 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds.

2020-07-05 11:37:25 ERROR (MainThread) [homeassistant.helpers.entity] Update for lock.kuche fails

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state

await self.async_device_update()

File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update

self.update # type: ignore

File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run

result = self.fn(*self.args, **self.kwargs)

File "/usr/src/homeassistant/homeassistant/components/nuki/lock.py", line 124, in update

self._nuki_device.update(aggressive=level)

File "/usr/local/lib/python3.7/site-packages/pynuki/device.py", line 90, in update

"Failed to update data for lock. "

AssertionError: Failed to update data for lock. Nuki ID None volatized.

2020-07-05 11:37:35 ERROR (SyncWorker_17) [homeassistant.components.command_line.sensor] Command failed: echo $ ((' cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2'))

 

 

And this is the state:

 

 



This are the data they correspond with the Vantage panel. Except the pressure shows 1016.7 vs 1018.5.



Von: Bjarne Riis <notifications@github.com> 
Gesendet: Sonntag, 5. Juli 2020 11:13
An: briis/meteobridge <meteobridge@noreply.github.com>
Cc: Peter Buehrer <peter@buehrer.com>; Author <author@noreply.github.com>
Betreff: Re: [briis/meteobridge] Some unknown errors (#3)

 

Hi Peter,
There are a lot of Non Meteobridge related errors in the above, but I can see that it complains about the Temperature value, and it seems that it has a ; attached to the end. I am a bit puzzled about this, as this should not could happen.
Can you go to the Developer Tab and press the STATES tab. And then find the sensor.temperature and let me know what that says? Are the other sensors from Meteobridge Working?

**Comment by briis** [comment]
Thanks. Again, only the first line in your log has anything to do with this Integration, the rest comes from other Integrations.
I think you might have tried to attach a picture, but I cannot see it - So is your Temperature showing correctly?

**Comment by legi1** [comment]
Yes, its correct. 

Sent from Nine
________________________________
Von: Bjarne Riis <notifications@github.com>
Gesendet: Sonntag, 5. Juli 2020 11:50
An: briis/meteobridge
Cc: Peter Buehrer; Author
Betreff: Re: [briis/meteobridge] Some unknown errors (#3) 

Thanks. Again, only the first line in your log has anything to do with this Integration, the rest comes from other Integrations.
I think you might have tried to attach a picture, but I cannot see it - So is your Temperature showing correctly?

**Comment by legi1** [comment]
Btw, sorry but I'm not too technically.... 

Sent from Nine
________________________________
Von: Bjarne Riis <notifications@github.com>
Gesendet: Sonntag, 5. Juli 2020 11:50
An: briis/meteobridge
Cc: Peter Buehrer; Author
Betreff: Re: [briis/meteobridge] Some unknown errors (#3) 

Thanks. Again, only the first line in your log has anything to do with this Integration, the rest comes from other Integrations.
I think you might have tried to attach a picture, but I cannot see it - So is your Temperature showing correctly?

**Comment by briis** [comment]
Could try and paste the following VERY long line in to a web-browser and copy the result and post it here. Replace the text YOURPASSWORD with the password you use for your Meteobridge Nano. That will give me the raw data that the Integration works with, and I can check if everything looks correct.
Copy things below here as one line:

http://meteobridge:YOURPASSWORD@192.168.1.209/cgi-bin/template.cgi?template=[DD]/[MM]/[YYYY];[hh]:[mm]:[ss];[th0temp-act:0];[thb0seapress-act:0];[th0hum-act:0];[wind0avgwind-act:0];[wind0dir-avg5.0:0];[rain0total-daysum:0];[rain0rate-act:0];[th0dew-act:0];[wind0chill-act:0];[wind0wind-max1:0];[th0lowbat-act.0:0];[thb0temp-act:0];[thb0hum-act.0:0];[th0temp-dmax:0];[th0temp-dmin:0];[wind0wind-act:0];[th0heatindex-act.1:0];[uv0index-act:0];[sol0rad-act:0];[th0temp-mmin.1:0];[th0temp-mmax.1:0];[th0temp-ymin.1:0];[th0temp-ymax.1:0];[wind0wind-mmax.1:0];[wind0wind-ymax.1:0];[rain0total-mmax.1:0];[rain0total-ymax.1:0];[rain0rate-mmax.1:0];[rain0rate-ymax.1:0];[lgt0total-act.0:0];[lgt0energy-act.0:0];[lgt0dist-act.0:0];[air0pm-act.0:0];[wind0wind-act=bft.0:0];[th1temp-act:0];[th1hum-act:0];[th1heatindex-act.1:0];[th2temp-act:0];[th2hum-act:0];[th2heatindex-act.1:0];[forecast-text:]

**Comment by legi1** [comment]
05/07/2020;12:23:49;24.3;1018.2;59.0;2.2;253;0.0;0.0;15.8;24.3;1.3;0;26.5;38;24.6;13.5;0.9;24.3;7.1;904.0;12.4;30.7;-4.9;30.7;11.6;20.6;5.7;197.8;44.0;822.9;0;0;0;0;1;0;0;0;0;0;0;Increasing clouds with little temperature change. Precipitation possible within 24 to 48 hours.

 

 

Von: Bjarne Riis <notifications@github.com> 
Gesendet: Sonntag, 5. Juli 2020 12:00
An: briis/meteobridge <meteobridge@noreply.github.com>
Cc: Peter Buehrer <peter@buehrer.com>; Author <author@noreply.github.com>
Betreff: Re: [briis/meteobridge] Some unknown errors (#3)

 

Could try and paste the following VERY long line in to a web-browser and copy the result and post it here. Replace the text YOURPASSWORD with the password you use for your Meteobridge Nano. That will give me the raw data that the Integration works with, and I can check if everything looks correct.
Copy things below here as one line:

http://meteobridge:DerVerkauf2019@192.168.1.209/cgi-bin/template.cgi?template=[DD]/[MM]/[YYYY];[hh]:[mm]:[ss];[th0temp-act:0];[thb0seapress-act:0];[th0hum-act:0];[wind0avgwind-act:0];[wind0dir-avg5.0:0];[rain0total-daysum:0];[rain0rate-act:0];[th0dew-act:0];[wind0chill-act:0];[wind0wind-max1:0];[th0lowbat-act.0:0];[thb0temp-act:0];[thb0hum-act.0:0];[th0temp-dmax:0];[th0temp-dmin:0];[wind0wind-act:0];[th0heatindex-act.1:0];[uv0index-act:0];[sol0rad-act:0];[th0temp-mmin.1:0];[th0temp-mmax.1:0];[th0temp-ymin.1:0];[th0temp-ymax.1:0];[wind0wind-mmax.1:0];[wind0wind-ymax.1:0];[rain0total-mmax.1:0];[rain0total-ymax.1:0];[rain0rate-mmax.1:0];[rain0rate-ymax.1:0];[lgt0total-act.0:0];[lgt0energy-act.0:0];[lgt0dist-act.0:0];[air0pm-act.0:0];[wind0wind-act=bft.0:0];[th1temp-act:0];[th1hum-act:0];[th1heatindex-act.1:0];[th2temp-act:0];[th2hum-act:0];[th2heatindex-act.1:0];[forecast-text:]

**Comment by legi1** [comment]
05/07/2020;12:23:49;24.3;1018.2;59.0;2.2;253;0.0;0.0;15.8;24.3;1.3;0;26.5;38;24.6;13.5;0.9;24.3;7.1;904.0;12.4;30.7;-4.9;30.7;11.6;20.6;5.7;197.8;44.0;822.9;0;0;0;0;1;0;0;0;0;0;0;Increasing clouds with little temperature change. Precipitation possible within 24 to 48 hours.

 

 

Von: Bjarne Riis <notifications@github.com> 
Gesendet: Sonntag, 5. Juli 2020 12:00
An: briis/meteobridge <meteobridge@noreply.github.com>
Cc: Peter Buehrer <peter@buehrer.com>; Author <author@noreply.github.com>
Betreff: Re: [briis/meteobridge] Some unknown errors (#3)

 

Could try and paste the following VERY long line in to a web-browser and copy the result and post it here. Replace the text YOURPASSWORD with the password you use for your Meteobridge Nano. That will give me the raw data that the Integration works with, and I can check if everything looks correct.
Copy things below here as one line:

http://meteobridge:YOURPASSWORD@192.168.1.209/cgi-bin/template.cgi?template=[DD]/[MM]/[YYYY];[hh]:[mm]:[ss];[th0temp-act:0];[thb0seapress-act:0];[th0hum-act:0];[wind0avgwind-act:0];[wind0dir-avg5.0:0];[rain0total-daysum:0];[rain0rate-act:0];[th0dew-act:0];[wind0chill-act:0];[wind0wind-max1:0];[th0lowbat-act.0:0];[thb0temp-act:0];[thb0hum-act.0:0];[th0temp-dmax:0];[th0temp-dmin:0];[wind0wind-act:0];[th0heatindex-act.1:0];[uv0index-act:0];[sol0rad-act:0];[th0temp-mmin.1:0];[th0temp-mmax.1:0];[th0temp-ymin.1:0];[th0temp-ymax.1:0];[wind0wind-mmax.1:0];[wind0wind-ymax.1:0];[rain0total-mmax.1:0];[rain0total-ymax.1:0];[rain0rate-mmax.1:0];[rain0rate-ymax.1:0];[lgt0total-act.0:0];[lgt0energy-act.0:0];[lgt0dist-act.0:0];[air0pm-act.0:0];[wind0wind-act=bft.0:0];[th1temp-act:0];[th1hum-act:0];[th1heatindex-act.1:0];[th2temp-act:0];[th2hum-act:0];[th2heatindex-act.1:0];[forecast-text:]

**Comment by briis** [comment]
Hi Peter,
There does not seem to be anything wrong with Meteobridge. The data you get from it are correct. In your log file you get this, related to Meteobridge:
`2020-07-05 11:37:01 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.temperature=24.2; attribution=Powered by Meteobridge, brand=Meteobridge, station_hw=Meteobridge Nano, station_ip=192.168.1.209, unit_of_measurement=°C, friendly_name=Temperature, icon=mdi:thermometer, device_class=temperature @ 2020-07-05T11:37:01.848489+02:00> (Offending entity: ?)`

Are you using the temperature sensor in a Template, because then that might be the where this error comes from. It does not come from the Integration.

**Comment by legi1** [comment]
Hi Bjarne

 

No problem with that. I just found this Log, not knowing anything on the meanings. I use this sensor to control 2 windows in some automations. So I will check what I’m doing there…

As a newbie in this area I have to learn a lot with the Home Assistant stuff. But is  very interesting what can be done with HA.

 

Thanks for your support and patience.

 

Cheers

Peter

 

Von: Bjarne Riis <notifications@github.com> 
Gesendet: Montag, 6. Juli 2020 06:56
An: briis/meteobridge <meteobridge@noreply.github.com>
Cc: Peter Buehrer <peter@buehrer.com>; Author <author@noreply.github.com>
Betreff: Re: [briis/meteobridge] Some unknown errors (#3)

 

Hi Peter,
There does not seem to be anything wrong with Meteobridge. The data you get from it are correct. In your log file you get this, related to Meteobridge:
2020-07-05 11:37:01 WARNING (MainThread) [homeassistant.helpers.condition] Value cannot be processed as a number: <state sensor.temperature=24.2; attribution=Powered by Meteobridge, brand=Meteobridge, station_hw=Meteobridge Nano, station_ip=192.168.1.209, unit_of_measurement=°C, friendly_name=Temperature, icon=mdi:thermometer, device_class=temperature @ 2020-07-05T11:37:01.848489+02:00> (Offending entity: ?)

Are you using the temperature sensor in a Template, because then that might be the where this error comes from. It does not come from the Integration.

**Comment by briis** [comment]
No problem. A good place to ask for help for Automations is in the [community forum](https://community.home-assistant.io/). Post your code there and someone might be able to help.

And yes, Home Assistant is fantastic, but due to the many things it can do, it can also be confusing. Try to do one thing at a time, that helped me.

I will close this now.
